#!/usr/bin/env php

<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

use Toolkit\Console\ProvisionCommand;

$application = new Application();
$application->add(new ProvisionCommand());
$application->run();
